/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class utils_linux_inotify_INotify_Subscription */

#ifndef _Included_utils_linux_inotify_INotify_Subscription
#define _Included_utils_linux_inotify_INotify_Subscription
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
