/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class utils_linux_inotify_INotify */

#ifndef _Included_utils_linux_inotify_INotify
#define _Included_utils_linux_inotify_INotify
#ifdef __cplusplus
extern "C" {
#endif
#undef utils_linux_inotify_INotify_IN_ACCESS
#define utils_linux_inotify_INotify_IN_ACCESS 1L
#undef utils_linux_inotify_INotify_IN_MODIFY
#define utils_linux_inotify_INotify_IN_MODIFY 2L
#undef utils_linux_inotify_INotify_IN_ATTRIB
#define utils_linux_inotify_INotify_IN_ATTRIB 4L
#undef utils_linux_inotify_INotify_IN_CLOSE_WRITE
#define utils_linux_inotify_INotify_IN_CLOSE_WRITE 8L
#undef utils_linux_inotify_INotify_IN_CLOSE_NOWRITE
#define utils_linux_inotify_INotify_IN_CLOSE_NOWRITE 16L
#undef utils_linux_inotify_INotify_IN_OPEN
#define utils_linux_inotify_INotify_IN_OPEN 32L
#undef utils_linux_inotify_INotify_IN_MOVED_FROM
#define utils_linux_inotify_INotify_IN_MOVED_FROM 64L
#undef utils_linux_inotify_INotify_IN_MOVED_TO
#define utils_linux_inotify_INotify_IN_MOVED_TO 128L
#undef utils_linux_inotify_INotify_IN_CREATE
#define utils_linux_inotify_INotify_IN_CREATE 256L
#undef utils_linux_inotify_INotify_IN_DELETE
#define utils_linux_inotify_INotify_IN_DELETE 512L
#undef utils_linux_inotify_INotify_IN_DELETE_SELF
#define utils_linux_inotify_INotify_IN_DELETE_SELF 1024L
#undef utils_linux_inotify_INotify_IN_MOVE_SELF
#define utils_linux_inotify_INotify_IN_MOVE_SELF 2048L
#undef utils_linux_inotify_INotify_IN_UNMOUNT
#define utils_linux_inotify_INotify_IN_UNMOUNT 8192L
#undef utils_linux_inotify_INotify_IN_Q_OVERFLOW
#define utils_linux_inotify_INotify_IN_Q_OVERFLOW 16384L
#undef utils_linux_inotify_INotify_IN_IGNORED
#define utils_linux_inotify_INotify_IN_IGNORED 32768L
#undef utils_linux_inotify_INotify_IN_CLOSE
#define utils_linux_inotify_INotify_IN_CLOSE 24L
#undef utils_linux_inotify_INotify_IN_MOVE
#define utils_linux_inotify_INotify_IN_MOVE 192L
#undef utils_linux_inotify_INotify_IN_ONLYDIR
#define utils_linux_inotify_INotify_IN_ONLYDIR 16777216L
#undef utils_linux_inotify_INotify_IN_DONT_FOLLOW
#define utils_linux_inotify_INotify_IN_DONT_FOLLOW 33554432L
#undef utils_linux_inotify_INotify_IN_EXCL_UNLINK
#define utils_linux_inotify_INotify_IN_EXCL_UNLINK 67108864L
#undef utils_linux_inotify_INotify_IN_MASK_ADD
#define utils_linux_inotify_INotify_IN_MASK_ADD 536870912L
#undef utils_linux_inotify_INotify_IN_ISDIR
#define utils_linux_inotify_INotify_IN_ISDIR 1073741824L
#undef utils_linux_inotify_INotify_IN_ONESHOT
#define utils_linux_inotify_INotify_IN_ONESHOT -2147483648L
#undef utils_linux_inotify_INotify_BUFFERSIZE
#define utils_linux_inotify_INotify_BUFFERSIZE 8192L
/*
 * Class:     utils_linux_inotify_INotify
 * Method:    init_class
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_utils_linux_inotify_INotify_init_1class
  (JNIEnv *, jclass);

/*
 * Class:     utils_linux_inotify_INotify
 * Method:    init
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_utils_linux_inotify_INotify_init
  (JNIEnv *, jobject, jint);

/*
 * Class:     utils_linux_inotify_INotify
 * Method:    add_watch
 * Signature: (Ljava/lang/String;I)I
 */
JNIEXPORT jint JNICALL Java_utils_linux_inotify_INotify_add_1watch
  (JNIEnv *, jobject, jstring, jint);

/*
 * Class:     utils_linux_inotify_INotify
 * Method:    rm_watch
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_utils_linux_inotify_INotify_rm_1watch
  (JNIEnv *, jobject, jint);

/*
 * Class:     utils_linux_inotify_INotify
 * Method:    getEvent
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_utils_linux_inotify_INotify_getEvent
  (JNIEnv *, jobject);

/*
 * Class:     utils_linux_inotify_INotify
 * Method:    close
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_utils_linux_inotify_INotify_close
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
